### ISSUE TITLE
can we get a release for admin plugin support?

### ISSUE THREAD

**Issue by jprobichaud** [trilbymedia/grav-plugin-login-oauth2#12]
I've seen some activity around this topic in March, but the current "official" plugin is still 1.0.2 and is pretty old.  Can we hope a release for this feature in a near future?  

It's really one of the pain points of Grav for us right now.

Thanks!

**Comment by drzraf** [comment]
@jprobichaud Sorry to ask you but aren't you affected by #11 ? `php-cli -S` / `php-fpm` ?

**Comment by rhukster** [comment]
i'm working on this guys.. i'll give you some updates soon.

**Comment by rhukster** [comment]
The update in develop should be good for testing if you guys wanna try it out?

**Comment by drzraf** [comment]
I tried latest `develop` (and improved configuration) + latest release of Grav 1.6.x + `admin-1.9.3 but I'm still held back by #11.

**Comment by rhukster** [comment]
2.0.0 has been released with admin support and some other improvements.

**Comment by jprobichaud** [comment]
works perfectly, even with git-sync.  Thanks!
