### ISSUE TITLE
update `oauth2-google` to 3.0.1

### ISSUE THREAD

**Issue by drzraf** [trilbymedia/grav-plugin-login-oauth2#13]
In latest release of `league/oauth2-google`, a fix was released for the error:
```
Access Not Configured. Google+ API has not been used in project XXX before or it is disabled.
Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=XXX
```

Updating the package will allow to use OpenId without having to enable the Google+ API or request additional (and unneeded) user details to the API.
(related to https://github.com/thephpleague/oauth2-google/issues/74)

**Comment by rhukster** [comment]
I'll take a look...

**Comment by rhukster** [comment]
Done, and also LinkedIn updated too.
