### ISSUE TITLE
login callback wrong redirect (if code contains slashes ?)

### ISSUE THREAD

**Issue by drzraf** [trilbymedia/grav-plugin-login-oauth2#14]
Whether a login succeeds or fails, `loginCallback()` terminates with `$this->grav->redirect($redirect);`

When I'm redirected to `/task:callback.oauth2`, the query string looks like:
- `state=LOGIN_OAUTH2_AOlXotmxyz`
- `code=4/OAGqIBDablmJabjLxyz`
- `scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile`
- `authuser=0`
- `hd=foo.org`
- `session_state=xxx`
- `prompt=none`

And the callback redirects (in both case) to:
**Location**: `/OAGqIBDablmJabjLxyz&scope=email%20profile%20openid%20https:/userinfo.email%20https:?state=LOGIN_OAUTH2_AOlXotmxyz&code=4%2FOAGqIBDablmJabjLxyz&scope=email%20profile%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&hd=foo.org&session_state=xxx&prompt=none`

This resource does not exist.
I think (but quite unsure) that it could be related to `$code` containing a `/` character.

**Comment by rhukster** [comment]
Is this based on the current `develop` branch or released version??

**Comment by rhukster** [comment]
Can you test with the commit mentioned above?

**Comment by drzraf** [comment]
Confirmed!
I'm now unconditionally redirected to the homepage.
Not as good as being redirected to /admin/ but better than an nonexistent page.

**Comment by rhukster** [comment]
Actually, it goes to the base of the redirect.. so if you have an admin redirect of `http://yoursite.com/admin/task:callback.oauth2` it will redirect to `http://yoursite.com/admin`. I realized the default redirect didn't have this, it will address some issues you are seeing.
