### ISSUE TITLE
Implements `default_groups` to complement `default_access_levels`

### ISSUE THREAD

**Issue by drzraf** [trilbymedia/grav-plugin-login-oauth2#15]
I don't know what implementation would be preferred:
1. Yet another option to set default groups
2. Extend `default_access_levels` to support groups instead of `accesses` only
3. something else.

Let me know, then I could possibly provide a patch.

**Comment by rhukster** [comment]
would need a new field i think.

**Comment by rhukster** [comment]
Added this to config/blueprints/readme.  cheers.
