### ISSUE TITLE
Can't install with latest Grav + Admin

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-login-oauth2#17]
When trying to install with the latest Grav + Admin I get the following error message:

![2019-04-27_11-35-34](https://user-images.githubusercontent.com/1812771/56867662-965cf580-699c-11e9-9465-3c06adce5f53.png)

Thanks very much,
Paul
ps - this was also reported by someone else in the Grav Discord Room

**Comment by rhukster** [comment]
Will fix shortly.  Cheers.

**Comment by rhukster** [comment]
Release v2.0.1.. should show up in 20 mins

**Comment by paulhibbitts** [comment]
Confirmed, thanks very much @rhukster and also for the awesome extra services incl GitLab👍
