### ISSUE TITLE
No Grav User gets stored in account folder

### ISSUE THREAD

**Issue by hansmans08** [trilbymedia/grav-plugin-login-oauth2#2]
Hi,

Login works fine. But after you get redirected from the Google-Authentication no Grav-User is stored and no User is getting logged in, although the settings are enabled. So you can't access the grav.user.username variable in the Twig-Template.

Don't really know whats wrong. Hope you can help.

**Comment by rhukster** [comment]
The creation of the local Grav user is a setting, so check that setting in the plugin configuration.  If you are not logged on when getting back to the site, then there's something wrong with the process.  Double check all the settings and ensure you have performed all the steps as specified in the README.md.
