### ISSUE TITLE
Do you know if Azure AAD auth works?

### ISSUE THREAD

**Issue by oppknox** [trilbymedia/grav-plugin-login-oauth2#26]
I see Oauth2 and openID work, and I see several specific providers called out but I dont see Microsoft listed, while I was under the impression this is an open standard? Thanks! (excited to give this a shot, it looks like you did some great work here!)

**Comment by lolrofllol** [comment]
We are planning to do the same in our environment. Did you manage to get it work with Azure AD?

**Comment by o1oo11oo** [comment]
We opened a pull request for this: trilbymedia/grav-plugin-login-oauth2-extras#1
