### ISSUE TITLE
Feature request: Auth0 Provider

### ISSUE THREAD

**Issue by RCheesley** [trilbymedia/grav-plugin-login-oauth2#27]
Hi folks,

It would be super helpful to include Auth0 as a provider, they are widely used and have a well documented platform.

This should be a good stepping off point: https://auth0.com/docs/protocols/oauth2

**Comment by RCheesley** [comment]
Been doing a bit of digging and it seems that Auth0 is a third party provider listed here: https://oauth2-client.thephpleague.com/providers/thirdparty/

Hopefully shouldn't be too much work to implement, is it just a case of creating the provider files and adding the appropriate fields?

Here's the repo for info:
https://github.com/RiskioFr/oauth2-auth0

**Comment by saitanay** [comment]
Raised a PR @ https://github.com/trilbymedia/grav-plugin-login-oauth2/pull/29

**Comment by saitanay** [comment]
Available as a separate plugin @
https://github.com/saitanay/grav-plugin-login-o-auth2-auth0

**Comment by rhukster** [comment]
Does this extend the base oauth2 plugin? If so I have a minor thing, can you change the repo to: `grav-plugin-login-oauth2-auth0` so it's in line with others that extend the base oauth2 plugin like: https://github.com/trilbymedia/grav-plugin-login-oauth2-apple

**Comment by saitanay** [comment]
@rhukster  - here you go - https://github.com/saitanay/grav-plugin-login-oauth2-auth0

**Comment by saitanay** [comment]
Updated https://github.com/getgrav/grav/issues/2830 as well.

**Comment by saitanay** [comment]
This issue could be closed now. 

https://github.com/saitanay/grav-plugin-login-oauth2-auth0
