### ISSUE TITLE
Feature: Support GitLab

### ISSUE THREAD

**Issue by AtjonTV** [trilbymedia/grav-plugin-login-oauth2#3]
It is cool to be able to use GitHub, but I love using GitLab.

It would be great to be able to use GitLab.com and a self hosted GitLab install.

The API calls between GitLab.com and any Self-Hosted GitLab are the same, how to use the API can be found [here](https://gitlab.com/help/api/README.md).

GitLab has integraded support for "System OAuth Applications", [here](https://docs.gitlab.com/ce/integration/oauth_provider.html) is also a tutorial for OAuth via GitLab.

There is also a user based "OAuth Applciation" within a users account, it can be found at &lt;gitlab-server&gt;/profile/applications (when loggedin), there is an Scope called "openid" with the description:

"The ability to authenticate using GitLab, and read-only access to the user's profile information and group memberships"

I am very thankfull when OAuth via GitLab (Gitlab.com and self-hosted) becomes a thing ;D

**Comment by w00fz** [comment]
Totally! I'll look into it.

**Comment by w00fz** [comment]
Implemented! 👍
