### ISSUE TITLE
Assigning OAuth2 to existing user

### ISSUE THREAD

**Issue by sandeepansg** [trilbymedia/grav-plugin-login-oauth2#35]
When I try to implement OAuth2 login in Admin panel, it creates a new admin user.
Eg. When implementing Github OAuth2 it creates a new admin user **github.(some number).(github username).yaml** but I want to bind this github OAuth2 SSO with existing default *admin.yaml*

I've tried copying the following snippet from *github.(some number).(github username).yaml* to **admin.yaml**
>token: '{"scope":"user","token_type":"bearer","access_token":" **REDACTED FOR SECURITY** "}'
provider: github

But it made no difference

Please guide me figuring this out

**Comment by mahagr** [comment]
Grav will now use the existing user (defined by email address) for OAuth2 logins.

If the user is found and has already used another provider (with `store_provider_data` and `save_grav_user` enabled), the login will fail and asks to use the same provider.

**Comment by mahagr** [comment]
(Fixed for the next release)
