### ISSUE TITLE
2fa bypassed when set on for user using oAuth2

### ISSUE THREAD

**Issue by Andy-Flack** [trilbymedia/grav-plugin-login-oauth2#39]
If the site has 2fa enabled and the user logging in via an oauth2 provider tries to activate 2fa, it has no effect and they are not even challenged.
I think this is because the oAuth2 authentication does not perform the final 'allow other plugins to refuse the connection' process. 

As my non-oAuth2 users have a higher degree of identity verification they are allowed to do more.

Does anyone know what the correct procedure would be for firing the 2fa check against an oAuth2 login?

**Comment by rhukster** [comment]
I think the 2fa has to provided by the oauth provide.  For example I have 2fa on GitHub, Google, Facebook, and Apple and have to perform their own 2fa checks before logging into any site with their oauth integration. If we supported our own 2fa for these, people would be forced to perform two checks.

**Comment by mahagr** [comment]
I agree. 2FA should be enabled in the login service, for example, Google is making 2FA mandatory. Having another 2FA check would just be annoying to people who'd need to pass 2 checks.
