### ISSUE TITLE
Problem with facebook login since 2.10

### ISSUE THREAD

**Issue by ghost** [trilbymedia/grav-plugin-login-oauth2#40]
Since commit 89fe1eec7ef3042ca3e292e03335ba801fee1c41, it is no longer possible to use facebook oauth for signin on site. The problem is this piece of code.

`if (!empty($options['enabled'])) {
       	$enabled = $options['enabled'] ?? false;
	$client_id = $options['client_id'] ?? false;
	if ($enabled && $client_id) {
		$this->addProvider($provider, $options);
	}
}`

It assumes there is a client_id defined for all auth providers, but actually there is not. Facebook seems to be the only provider which doesn't use a client_id. This mistake simply means that the facebook icon on the login page is never shown.

**Comment by w00fz** [comment]
Thanks for reporting this

**Comment by rhukster** [comment]
Fixed and released.. look for 2.1.1 in about 30 mins.
