### ISSUE TITLE
Feature: Discord support?

### ISSUE THREAD

**Issue by SynthSy** [trilbymedia/grav-plugin-login-oauth2#5]
Is there a way that we could have Discord support?

There's a 3rd party plugin for League, and I was wondering if there's a way to go about adding it in.

By the way, great plugin! Currently using the github part of the plugin.

**Comment by rhukster** [comment]
I already did one: https://github.com/trilbymedia/grav-plugin-login-oauth2-discord

Not fully tested and released yet.  Can you please test it?

**Comment by SynthSy** [comment]
Works great so far.

**Comment by rhukster** [comment]
Moved to this: https://github.com/trilbymedia/grav-plugin-login-oauth2-extras
