### ISSUE TITLE
[FR] Azure AD Support

### ISSUE THREAD

**Issue by timcappalli** [trilbymedia/grav-plugin-login-oauth2#6]
Would be great to have Azure AD as a provider

**Comment by mopede80** [comment]
Can only second that. Azure AD provider support would be very nice indeed.

**Comment by dkoryto** [comment]
or Office 365.

**Comment by rhukster** [comment]
Looks like there is a compatible library, so should be doable...

https://github.com/TheNetworg/oauth2-azure

**Comment by rhukster** [comment]
Please make a Pull Request against this: https://github.com/trilbymedia/grav-plugin-login-oauth2-extras

I really have no interest in setting up an Azure test site because last time I tried that I got billed for months after I canceled it.
